name: Deploy Angular App to S3

on:
  push:
    branches:
      - master  # Asegúrate de usar la rama correcta de tu repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Usa una versión de Node.js compatible

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build --prod  # Este comando debe coincidir con tu script de build en package.json

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Sync S3 bucket
      run: aws s3 sync ./dist/my-portfolio/browser s3://my-web-portfolio-paul --delete --cache-control "max-age=3600"
